config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :schedules
  resources :trainers do
    resources :comments
  end
  root to: 'pages#home'
  devise_for :users do
  	resources :comments
  end
  get "/pages", to: "pages#home"
  get "/courses", to: "courses#home"
  get '/search' => 'pages#search', :as => 'search_page'
  post "/", to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  # relationship with trainer to include trainer_id in the new schedule form
  belongs_to :trainer, :inverse_of => :schedules
  # relationship with trainer to include trainer_id in the new schedule form
  belongs_to :course, :inverse_of => :schedules
  #accepts_nested_attributes_for :trainer
 
  # validation to check if the start time for the same trainer is already booked.  this way users cannot book the same start time once it is already scheduled with that specific trainer. 
  validates :start_time, uniqueness: { scope: :trainer_id, message: "You have already made this time available" }
  
  amoeba do
    enable
    exclude_associations :bookings
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  # check if user is logged in before loading the page
  before_action :authenticate_user!
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  
  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:title, :start_time, :end_time, :trainer_id, :course_id)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<div class="container">  
  <%= form_with(model: schedule, local: true) do |form| %>
    <% if schedule.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

        <ul>
        <% schedule.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

<div class="container has-text-centered">
    <div class="column is-4 is-offset-4">
    <div class="field">
      <%= form.label :title, class: "label is-medium"%>
      <%= form.text_field :title, class: "input is-medium"%>
    </div>

    <div class="field">
      <div class="select is-medium is-fullwidth">
      <%= form.label :trainer, class: "label is-medium"%>
      <%= form.collection_select(:trainer_id, Trainer.all, :id, :first_name)%>
    </div>
    </div>
    <br/>
    <div class="field">
      <div class="select is-medium is-fullwidth">
      <%= form.label :course_id, class: "label is-medium" %>
      <%= form.collection_select(:course_id, Course.all, :id, :course_name) %>
    </div>
    </div>
    <br/>
    <br/>
    <div class="field">
     <%= form.label :start_time,  class: "label is-medium" %>
      <%= form.datetime_select :start_time,
        {ampm: true,
        ignore_date: false,
        start_hour: 8, 
        end_hour: 17,
        discard_minute: true,
        prompt: true,
        prompt: { hour: "Choose hr" },
        :start_year => 2019}, class: "input is-medium"
      %>
    </div>


    <div class="actions">
      <%= form.submit class: "button is-block is-success is-medium is-fullwidth" %>
    </div>
  <% end %>
  </div>
</div> 

</div>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="~bulma-calendar/dist/css/bulma-calendar.min.css" rel="stylesheet">
  <script src="~bulma-calendar/dist/js/bulma-calendar.min.js"></script>
</head>
<body>

<div class="container text-center" id="schedules">
  <p id="notice"><%= notice %></p>

  <h1>Schedules</h1>

  <table class="table is-bordered is-hoverable is-fullwidth">
    <thead>
      <tr class="is-selected">
        <th>Title</th>
        <th>Start time</th>
        <th>Trainer</th>
        <th>Course</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @schedules.each do |schedule| %>
        <tr>
          <td><%= schedule.title %></td>
          <td><%= schedule.start_time %></td>
          <td><%= schedule.trainer_id %></td>
          <td><%= schedule.course_id %></td>
          <td><%= link_to 'Show', schedule %></td>
          <% if current_user && current_user.admin? %>
            <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
            <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <a class="button is-primary" href="schedules/new" role="button">
    Book Appointment
  </a>

  <br>
  <br>

<div class="column is-fullwidth">
  <div class="calendar">
  <%= month_calendar events: @schedules do |date, schedules| %>
    <%= date %>

    <% schedules.each do |schedule| %>
      <div>
        <%= link_to schedule.title, schedule %>
        <br>  
        <%= schedule.start_time %>
      </div>
    <% end %>
  <% end %>
</div>
</div>
</div>
</body>
</html>

app/views/schedules/new.html.erb
<div class="container has-text-centered">
    <div class="column is-4 is-offset-4">
		<h1>New Schedule Form</h1>
	</div>
</div>
<%= render 'form', schedule: @schedule %>

<div class="container has-text-centered">
	<div class="column is-4 is-offset-4">
<%= link_to 'Back', schedules_path, class: "button is-block is-info is-medium is-vcentered" %>
</div>
</div>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table is-bordered is-hoverable is-fullwidth">
	<thead>
      <tr class="is-selected">
        <th>Title</th>
        <th>Start time</th>
        <th>Trainer</th>
        <th>Course</th>
      </tr>
    </thead>

    <tbody>
    	<tr>
          <td><%= @schedule.title %></td>
          <td><%= @schedule.start_time %></td>
          <td><%= @schedule.trainer_id %></td>
          <td><%= @schedule.course_id %></td>
        </tr>
    </tbody>
</table>
<% if current_user && current_user.admin? %>
<%= link_to 'Edit', edit_schedule_path(@schedule) %> <br>
<% end %>
<%= link_to 'Back', schedules_path %>