config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :schedules
  resources :trainers do
    resources :comments
  end
  root to: 'pages#home'
  devise_for :users do
  	resources :comments
  end
  get "/pages", to: "pages#home"
  get "/courses", to: "courses#home"
  get '/search' => 'pages#search', :as => 'search_page'
  post "/", to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  # relationship: Trainer table has many comments per Trainer
  has_many :comments
  # relationship: Trainer table has many schedules per Trainer
  has_many :schedules, dependent: :destroy, :inverse_of => :trainer
  accepts_nested_attributes_for :schedules
  #scope by_name  order(:first_name)

  # method to get the fullname by getting the first and last names from the db
  def name 
    "#{first_name} #{last_name}"
  end
  
  def email
    User.find_by_id(self.user_id)
  end

end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  # check if user is logged in and show page, only show the index and show methods if not logged in
  before_action :authenticate_user!, except: [:index, :show]
  #  check if the user is an admin and show the edit update and destroy methods if they are an admin
  before_action :ensure_admin, except: [:index, :show]
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]

  # GET /trainers
  # GET /trainers.json
  def index
    @trainers = Trainer.all
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainer }
      else
        format.html { render :edit }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: 'Trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:photo, :first_name, :last_name, :phone, :bio, :experience)
    end

    def ensure_admin
      unless current_user.admin?
        redirect_to(trainers_path, notice: 'Not authorized to create a Trainer')
      end
    end
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/_form.html.erb
<%= form_with(model: trainer, local: true) do |form| %>
  <% if trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

      <ul>
      <% trainer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container has-text-centered">
    <div class="column is-4 is-offset-4">
  <div class="field">
    <%= form.label :first_name, class: "label is-medium" %>
    <%= form.text_field :first_name, class: "input is-medium" %>
  </div>

  <div class="field">
    <%= form.label :last_name, class: "label is-medium" %>
    <%= form.text_field :last_name, class: "input is-medium"  %>
  </div>

  <div class="field">
    <%= form.label :phone, class: "label is-medium" %>
    <%= form.text_field :phone, class: "input is-medium"  %>
  </div>

  <div class="field">
    <%= form.label :bio, class: "label is-medium" %>
    <%= form.text_area :bio, class: "input is-medium"  %>
  </div>

  <div class="field">
    <%= form.label :experience, class: "label is-medium" %>
    <%= form.text_field :experience, class: "input is-medium"  %>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-block is-success is-medium is-fullwidth" %>
  </div>
</div>
</div>
<% end %>

app/views/trainers/edit.html.erb
<h1>Editing Trainer</h1>

<%= render 'form', trainer: @trainer %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trainers</h1>

<% @trainers.each do |trainer| %>
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-64x64">
        <%=image_tag("user.png")%>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= trainer.first_name %></strong><strong><%= trainer.last_name %></strong><small>     </small><small><%= trainer.experience %> Experience</small>
          <br>
          <%= trainer.bio %>
          <br>
          <p><b>Contact No:</b> <%= trainer.phone %></p>
          <div class="container">
    <div class="column is-2">
          <%= link_to 'Show', trainer, class: "button is-rounded is-success is-small" %>
        <% if current_user && current_user.admin? %>
          <%= link_to 'Edit', edit_trainer_path(trainer),  class: "button is-rounded is-primary is-small" %>
          <%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' },  class: "button is-rounded is-danger is-small" %>
        <% end %>
    </div>
  </div>  
        </p>
      </div>
    </div>
  </article>
</div>
<% end %>

<br>

<a class="button is-primary" href="trainers/new" role="button">
  New Trainer
</a>

app/views/trainers/new.html.erb
<div class="container has-text-centered">
    <div class="column is-4 is-offset-4">
		<h1>New Trainer Form</h1>
	</div>
</div>
<%= render 'form', trainer: @trainer %>

<div class="container has-text-centered">
    <div class="column is-4 is-offset-4">

<%= link_to 'Back', trainers_path, class: "button is-block is-info is-medium is-vcentered" %>

</div>
</div>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-64x64">
        <%=image_tag("user.png")%>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= @trainer.first_name %></strong><strong><%= @trainer.last_name %></strong><small>     </small><small><%= @trainer.experience %> Experience</small>
          <br>
          <%= @trainer.bio %>
          <br>
          <%= @trainer.phone %>
        </p>
      </div>
    </div>
  </article>
</div>

<h2> <%= @trainer.comments.count %> Comments</h2>
    <%= render @trainer.comments %>
    <% if current_user %>
    <div class="container has-text-centered">
    <div class="column is-4 is-offset-4">
    <h3>Add a Comment: </h3>
  </div>
</div>
    <%= render 'comments/form' %>
<br>
<%= link_to 'Edit', edit_trainer_path(@trainer) %> <br>
<% end %>
<%= link_to 'Back', trainers_path %>